### ISSUE TITLE
Synergy

### ISSUE THREAD

**Issue by valerio-bozzolan** [ItalianLinuxSociety/spid-wordpress#1]
Ciao gentilissimo @umbros! :)

Stasera 19 aprile dalle 20:00 alle 23:20 siamo disponibili per un aiuto da remoto. Tu saresti per caso disponibile per qualche botta-risposta in instant messaging (IRC / Telegram / Jitsi)?

**Comment by umbros** [comment]
Ciao Valerio, scusami ma sono stati giorni pieni pieni... sono disponibile anche questo weekend... dimmi tu giorno e orario e ci sentiamo va benissimo jitsi...

**Comment by valerio-bozzolan** [comment]
@umbros Probabilmente potrei domenica prima di cena o dopo cena. È un orario sensato?

**Comment by valerio-bozzolan** [comment]
Nuovi appuntamenti qui:

https://forum.italia.it/t/spid-weekly-meeting/276
